language: ruby
rvm:
  - 2.0.0-p247
  - 2.3.1
before_install:
  - gem update --system
  - gem install bundler
install: bundle install
script: bundle exec rspec
after_success: bundle exec gem build sourcerer.gemspec
deploy:
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file: sourcerer_*.gem
    api_key:
      secure: T82NpMoMYEEZQKz9a8O7qHRtuPC6u2cxfDuacD60hbwmFQ+INsJz3k9T6stmUUjEWyZDLwjtex6LaUnTftURvvvrkMtCLWleGJBXK2IhPAh3nTqh0I87j49FrTyytRhO4oN8bX8+M8C22fyNwN/VJiHYrfbKgvgh2manXWBNhCQ=
    on:
      repo: brewster1134/sourcerer
      ruby: 2.0.0-p247
      tags: true
  - provider: rubygems
    gem: sourcerer_
    gemspec: sourcerer_.gemspec
    skip_cleanup: true
    api_key:
      secure: tBgVMYWg3xUKbKW0VmBfF+yr7lBzJfynWWLknIZ4Kco+dpGM4e91bQp8fSm0fO7h1KKpfAoIYNJzzhShD7RmnnC1+yym6VgHdVRYp/7/golH1YDL3Ff8B4ggNU34bLQ9loL/o6dwblkTVzM8++ghFNpIcgxdIMpOyDeiofVjTsE=
    on:
      branch: master
      repo: brewster1134/sourcerer
      ruby: 2.0.0-p247
      tags: true
