language: ruby
install: bundle install
script: bundle exec rspec
rvm:
  - 2.0.0-p247
  - 2.3.1
deploy:
  - provider: rubygems
    gem: sourcerer_
    gemspec: sourcerer.gemspec
    skip_cleanup: true
    api_key:
      secure: guXzjSL1dN/gEYTCHMGofh9jA55Yzx9Um+TkoXidUTR8O84kAoL1sgd6zWOxmJuJFZnXadcQpNW3hts7Ab2oJBBad9w4XaGPh136c+NwRukNqbPxKfpHePMFQLkFnRFW3mc0b+zDSK4iMAbxUO3SUlGG4PuHr7sbu78F4cNokN4=
    on:
      branch: master
      repo: brewster1134/sourcerer
      ruby: 2.0.0-p247
      tags: true
